version: 2.0
jobs:
 Build-Terr:
   docker:
     - image: alpine:3.7
   steps:
     - checkout
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'
           apt-get update && apt-get install -y awscli
           aws --version

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Build-Terr

