version: 2.0
jobs:
 Build-Terr:
   docker:
     - image: ubuntu:16.04
   steps:
     - checkout
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'
     - run:
         name: AWS CLI Installation and Configuration
         command: |
           apt-get update && apt-get install -y awscli
           aws --version
           aws configure -- profile
     - run:
         name: Terraform
         command: |
           apt-get update && apt-get install -y wget
           apt-get update && apt-get install -y unzip
           wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
           unzip terraform_0.11.11_linux_amd64.zip
           install terraform /usr/local/bin
           terraform --version
     - run:
         name: Move to work dir
         command: |
           cd Terraform/dev
           ls -al
           
     - run:
         name: Initiate Terraform
         command: |
           terraform init
           terraform plan
           
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Build-Terr

