version: 2.0
orbs:
  aws-cli: circleci/aws-cli@0.1.1
jobs:
 Build-Terr:
   docker:
     - image: ubuntu:16.04
   aws-cli:
    executor: aws-cli/default

   steps:
     - checkout
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'
     - run:
         name: AWS CLI Installation
         command: |
           apt-get update && apt-get install -y awscli
           apt-get install -y python-pip python-dev build-essential 
           pip install --upgrade awscli
           aws --version
     - run:
         name: AWS CLI Installation
         command: |           
           export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
           export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
           export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
           export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
           aws configure
           
     - run:
         name: Terraform
         command: |
           apt-get update && apt-get install -y wget
           apt-get update && apt-get install -y unzip
           wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
           unzip terraform_0.11.11_linux_amd64.zip
           install terraform /usr/local/bin
           terraform --version
     - run:
         name: Move to work dir
         command: |
           cd Terraform/dev
           ls -al
           
     - run:
         name: Initiate Terraform
         command: |
           terraform init
           terraform plan
           
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Build-Terr

